# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingItem',
        ),
    ]
